name: Daily R devel and R patched build

on:
  workflow_dispatch:
  schedule:
    - cron:  '55 6 * * *'

jobs:

  daily-builds:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
        - { r: 'devel' }
        - { r: 'patched' }

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Docker build
      uses: r-hub/actions/docker-build@feature/arm64
      with:
        r_version: ${{ matrix.config.r }}
        docker_name: rhub/r-minimal
        github_name: r-hub/r-minimal/r-minimal
        docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        docker_password: ${{ secrets.DOCKER_HUB_TOKEN }}
        github_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        extra_tags: ${{ matrix.config.extra_tags }}
